osx_image: xcode10.2
language: objective-c
sudo: required

cache:
  directories:
  - Carthage

env:
  global:
    - PROJECT="RemakeStore.xcodeproj"
    - SCHEME="RemakeStore"
    - IOS_SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=12.2"
    - FRAMEWORK="RemakeStore"
    - CODE_COV_TOKEN="c826c35f-6230-414e-b819-d8b61a733bba"

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - brew install swiftlint
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds

script:
  - set -o pipefail
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$IOS_SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -j RemakeStore --cover-xml